#ifndef $(GUILAYOUT_NAME_UPPERCASE)_H
#define $(GUILAYOUT_NAME_UPPERCASE)_H

#include "raygui.h"

#define $(GUILAYOUT_NAME_UPPERCASE)_WIDTH $(GUILAYOUT_WINDOW_WIDTH)
#define $(GUILAYOUT_NAME_UPPERCASE)_HEIGHT $(GUILAYOUT_WINDOW_HEIGHT)

$(GUILAYOUT_STRUCT_TYPE)

// Forward declarations for functions defined at $(GUILAYOUT_NAME).c implementation file
$(GUILAYOUT_FUNCTIONS_DECLARATION_H)

#endif //!$(GUILAYOUT_NAME_UPPERCASE)_H